# Generated by Django 4.1.4 on 2022-12-27 16:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0002_candidateapplied'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CandidateApplied',
            new_name='CandidatesApplied',
        ),
    ]
